import { createTokens } from "tamagui";
import color from "./colors.json";
//https://tamagui.dev/docs/core/tokens
export const tokens = createTokens({
    color,
    size: {
        true: 20,
        s: 20,
        sm: 24,
        md: 28,
        lg: 32,
        xl: 36,
        '2xl': 40,
    },
    zIndex: {
        true: 0,
        none: 0,
        xs: 100,
        sm: 200,
        md: 300,
        lg: 400,
        xl: 500,
        xxl: 600,
        xxxl: 700,
    },
    radius: {
        s: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 32,
    },
    space: {
        true: 0,
        none: 0,
        xxxs: 2,
        xxs: 4,
        xs: 8,
        sm: 12,
        md: 16,
        lg: 20,
        xl: 24,
        xxl: 32,
        xxxl: 40,
    },
    //custom accessed with "$nameOfToken.variableName"
    iconSize: {
        xxs: 8,
        xs: 10,
        sm: 12,
        md: 16,
        lg: 20,
        xl: 24,
        xxl: 28,
        xxxl: 32,
    },
    padding: {
        none: 0,
        xxxs: 2,
        xxs: 4,
        xs: 6,
        sm: 8,
        md: 10,
        lg: 12,
        xl: 16,
        xxl: 24,
        xxxl: 18,
        '4xl': 20,
        '5xl': 28,
    },
    gap: {
        xxs: 2,
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        xxl: 32,
        xxxl: 40,
    },
    fontSize: {
        xxs: 10,
        xs: 12,
        sm: 14,
        md: 16,
        lg: 20,
        xl: 24,
        xxl: 28,
        xxxl: 32,
    }
});